
# spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/garbage_sorting?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: xqx1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 日志配置
logging:
  level:
    com:
      longder: DEBUG
# 系统端口
server:
  port: 5918
